/* Copyright(C) 2014 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.irzimbabwe.shared.model;

// Generated Nov 20, 2012 3:57:28 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Referral generated by hbm2java
 */
public class Referral implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 8402215983814049042L;
	private String	patientId;
	private String	referredBy;
	private String	referredTo;
	private String	reason;
	private Date	dateReferred;

	public Referral ()
	{
	}

	public Referral (String patientId)
	{
		this.patientId = patientId;
	}

	public Referral (String patientId, String referredBy, String referredTo, String reason, Date dateReferred)
	{
		this.patientId = patientId;
		this.referredBy = referredBy;
		this.referredTo = referredTo;
		this.reason = reason;
		this.dateReferred = dateReferred;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public String getReferredBy ()
	{
		return this.referredBy;
	}

	public void setReferredBy (String referredBy)
	{
		this.referredBy = referredBy;
	}

	public String getReferredTo ()
	{
		return this.referredTo;
	}

	public void setReferredTo (String referredTo)
	{
		this.referredTo = referredTo;
	}

	public String getReason ()
	{
		return this.reason;
	}

	public void setReason (String reason)
	{
		this.reason = reason;
	}

	public Date getDateReferred ()
	{
		return this.dateReferred;
	}

	public void setDateReferred (Date dateReferred)
	{
		this.dateReferred = dateReferred;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return patientId + ", " + referredBy + ", " + referredTo + ", " + reason + ", " + dateReferred;
	}
}
