/* Copyright(C) 2014 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.irzimbabwe.shared.model;

// Generated Jan 15, 2013 5:34:55 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SmsText generated by hbm2java
 */
public class SmsText implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -182967597455844870L;
	private Integer	textId;
	private String	ruleId;
	private String	text;
	private String	languageId;
	private String	description;

	public SmsText ()
	{
	}

	public SmsText (String ruleId, String text, String languageId, String description)
	{
		this.ruleId = ruleId;
		this.text = text;
		this.languageId = languageId;
		this.description = description;
	}

	public Integer getTextId ()
	{
		return this.textId;
	}

	public void setTextId (Integer textId)
	{
		this.textId = textId;
	}

	public String getRuleId ()
	{
		return this.ruleId;
	}

	public void setRuleId (String ruleId)
	{
		this.ruleId = ruleId;
	}

	public String getText ()
	{
		return this.text;
	}

	public void setText (String text)
	{
		this.text = text;
	}

	public String getLanguageId ()
	{
		return this.languageId;
	}

	public void setLanguageId (String languageId)
	{
		this.languageId = languageId;
	}

	public String getDescription ()
	{
		return this.description;
	}

	public void setDescription (String description)
	{
		this.description = description;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return textId + ", " + ruleId + ", " + text + ", " + languageId + ", " + description;
	}

}
