/* Copyright(C) 2014 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.irzimbabwe.shared.model;

// Generated Nov 19, 2012 3:38:13 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SmearTestId generated by hbm2java
 */
public class SputumTestId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -5382066684339956571L;
	private String	patientId;
	private int		sampleNo;

	public SputumTestId ()
	{
	}

	public SputumTestId (String patientId, int sampleNo)
	{
		this.patientId = patientId;
		this.sampleNo = sampleNo;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public int getSampleNo ()
	{
		return this.sampleNo;
	}

	public void setSampleNo (int sampleNo)
	{
		this.sampleNo = sampleNo;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SputumTestId))
			return false;
		SputumTestId castOther = (SputumTestId) other;

		return ((this.getPatientId () == castOther.getPatientId ()) || (this.getPatientId () != null && castOther.getPatientId () != null && this.getPatientId ().equals (castOther.getPatientId ())))
				&& (this.getSampleNo () == castOther.getSampleNo ());
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + (getPatientId () == null ? 0 : this.getPatientId ().hashCode ());
		result = 37 * result + this.getSampleNo ();
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return patientId + ", " + sampleNo;
	}
}
